//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookContent
    {
        public int BookContentId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Text { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
