//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EightLine
    {
        public int EightLineId { get; set; }
        public string EightLineText { get; set; }
    }
}
