//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWayData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPhotoData
    {
        public int PhotoId { get; set; }
        public string Caption { get; set; }
        public System.DateTime PhotoDate { get; set; }
    }
}
